//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommons.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ECommons.Resources.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Donate via Cryptocurrency 的本地化字符串。
        /// </summary>
        internal static string Context_CryptoDonation {
            get {
                return ResourceManager.GetString("Context_CryptoDonation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Explore other NightmareXIV plugins 的本地化字符串。
        /// </summary>
        internal static string Context_ExploreOtherPlugins {
            get {
                return ResourceManager.GetString("Context_ExploreOtherPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Join NightmareXIV Discord 的本地化字符串。
        /// </summary>
        internal static string Context_JoinDiscord {
            get {
                return ResourceManager.GetString("Context_JoinDiscord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Donate one-time via Ko-Fi 的本地化字符串。
        /// </summary>
        internal static string Context_OneTimeDonate {
            get {
                return ResourceManager.GetString("Context_OneTimeDonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subscribe on Patreon 的本地化字符串。
        /// </summary>
        internal static string Context_Subscribe {
            get {
                return ResourceManager.GetString("Context_Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Join Patreon 的本地化字符串。
        /// </summary>
        internal static string JoinPatreon {
            get {
                return ResourceManager.GetString("JoinPatreon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If you like this plugin, please consider supporting it via NightmareXIV Patreon or via other means! This will help the developer to keep it updated and maintained. And you will get additional benefits, such as priority support, access to private plugins and priority feature requests as well.
        ///
        ///Left click - to go to Patreon;
        ///Right click - see all options 的本地化字符串。
        /// </summary>
        internal static string PatreonButtonTooltip {
            get {
                return ResourceManager.GetString("PatreonButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If you like this plugin, please consider supporting it.
        ///
        ///Left click - to go to Patreon;
        ///Right click - see other options 的本地化字符串。
        /// </summary>
        internal static string SmallPatreonButtonTooltip {
            get {
                return ResourceManager.GetString("SmallPatreonButtonTooltip", resourceCulture);
            }
        }
    }
}
